In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('G:/SEM 5/mini-project/dataset/test_data.csv', header=0)

In [3]:
df

,Timestamp,Applied Mathematics - III,Applied Mathematics - IV,Discrete Structure and Graph Theory,Data Structures,Analysis Of Algorithm,Skill Based Lab (Java),Skill Based Lab (Python),SEM III Project Marks,SEM IV Project Marks,Member of any Student Chapter,GPA_SEM_III,GP_SEM_IV,Number of Internships Completed/ Ongoing,Attendance
0,2021/09/27 3:17:41 pm GMT+5:30,94,93,82,70,86,47,46,NaN,NaN,NaN,9.08,9.56,NaN,NaN
1,2021/09/27 3:18:59 pm GMT+5:30,90,79,64,80,70,46,37,NaN,NaN,NaN,8.77,8.52,NaN,NaN
2,2021/09/27 3:21:14 pm GMT+5:30,19,71,48,40,49,42,35,NaN,NaN,NaN,0.00,7.00,NaN,NaN
3,2021/09/27 3:22:52 pm GMT+5:30,71,69,62,54,65,46,38,NaN,NaN,NaN,7.31,8.07,NaN,NaN
4,2021/09/27 3:24:11 pm GMT+5:30,64,80,62,43,69,45,32,NaN,NaN,NaN,6.96,8.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,2021/09/27 6:33:17 pm GMT+5:30,39,32,43,36,46,47,38,NaN,NaN,NaN,0.00,0.00,NaN,NaN
111,2021/09/27 6:34:25 pm GMT+5:30,30,49,51,40,46,46,37,NaN,NaN,NaN,0.00,6.85,NaN,NaN
112,2021/09/27 6:35:25 pm GMT+5:30,55,68,66,64,66,45,46,NaN,NaN,NaN,7.08,7.52,NaN,NaN
113,2021/09/27 6:36:49 pm GMT+5:30,31,19,50,44,47,45,30,NaN,NaN,NaN,0.00,0.00,NaN,NaN
114,2021/09/27 6:37:59 pm GMT+5:30,47,47,43,42,55,45,35,NaN,NaN,NaN,0.00,6.93,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Timestamp                                 115 non-null    object
 1   Applied Mathematics - III                 115 non-null    int64
 2   Applied Mathematics - IV                  115 non-null    int64
 3   Discrete Structure and Graph Theory       115 non-null    int64
 4   Data Structures                           115 non-null    int64
 5   Analysis Of Algorithm                     115 non-null    int64
 6   Skill Based Lab (Java)                    115 non-null    int64
 7   Skill Based Lab (Python)                  115 non-null    int64
 8   SEM III Project Marks                     0 non-null      float64
 9   SEM IV Project Marks                      0 non-null      float64
 10  Member of any Student Chapter             0 non-null      float64
 11  GPA_SEM_III                               115 non-null    float64
 12  GP_SEM_IV                                 115 non-null    float64
 13  Number of Internships Completed/ Ongoing  0 non-null      float64
 14  Attendance                                0 non-null      float64
dtypes: float64(7), int64(7), object(1)
memory usage: 13.6+ KB

In [5]:
df.head()

,Timestamp,Applied Mathematics - III,Applied Mathematics - IV,Discrete Structure and Graph Theory,Data Structures,Analysis Of Algorithm,Skill Based Lab (Java),Skill Based Lab (Python),SEM III Project Marks,SEM IV Project Marks,Member of any Student Chapter,GPA_SEM_III,GP_SEM_IV,Number of Internships Completed/ Ongoing,Attendance
0,2021/09/27 3:17:41 pm GMT+5:30,94,93,82,70,86,47,46,NaN,NaN,NaN,9.08,9.56,NaN,NaN
1,2021/09/27 3:18:59 pm GMT+5:30,90,79,64,80,70,46,37,NaN,NaN,NaN,8.77,8.52,NaN,NaN
2,2021/09/27 3:21:14 pm GMT+5:30,19,71,48,40,49,42,35,NaN,NaN,NaN,0.00,7.00,NaN,NaN
3,2021/09/27 3:22:52 pm GMT+5:30,71,69,62,54,65,46,38,NaN,NaN,NaN,7.31,8.07,NaN,NaN
4,2021/09/27 3:24:11 pm GMT+5:30,64,80,62,43,69,45,32,NaN,NaN,NaN,6.96,8.00,NaN,NaN

In [6]:
df.shape

(115, 15)

In [7]:
df.describe

<bound method NDFrame.describe of                           Timestamp  Applied Mathematics - III  \
0    2021/09/27 3:17:41 pm GMT+5:30                         94
1    2021/09/27 3:18:59 pm GMT+5:30                         90
2    2021/09/27 3:21:14 pm GMT+5:30                         19
3    2021/09/27 3:22:52 pm GMT+5:30                         71
4    2021/09/27 3:24:11 pm GMT+5:30                         64
..                              ...                        ...
110  2021/09/27 6:33:17 pm GMT+5:30                         39
111  2021/09/27 6:34:25 pm GMT+5:30                         30
112  2021/09/27 6:35:25 pm GMT+5:30                         55
113  2021/09/27 6:36:49 pm GMT+5:30                         31
114  2021/09/27 6:37:59 pm GMT+5:30                         47

     Applied Mathematics - IV  Discrete Structure and Graph Theory  \
0                          93                                   82
1                          79                                   64
2                          71                                   48
3                          69                                   62
4                          80                                   62
..                        ...                                  ...
110                        32                                   43
111                        49                                   51
112                        68                                   66
113                        19                                   50
114                        47                                   43

     Data Structures  Analysis Of Algorithm  Skill Based Lab (Java)  \
0                 70                     86                      47
1                 80                     70                      46
2                 40                     49                      42
3                 54                     65                      46
4                 43                     69                      45
..               ...                    ...                     ...
110               36                     46                      47
111               40                     46                      46
112               64                     66                      45
113               44                     47                      45
114               42                     55                      45

     Skill Based Lab (Python)  SEM III Project Marks  SEM IV Project Marks  \
0                          46                    NaN                   NaN
1                          37                    NaN                   NaN
2                          35                    NaN                   NaN
3                          38                    NaN                   NaN
4                          32                    NaN                   NaN
..                        ...                    ...                   ...
110                        38                    NaN                   NaN
111                        37                    NaN                   NaN
112                        46                    NaN                   NaN
113                        30                    NaN                   NaN
114                        35                    NaN                   NaN

     Member of any Student Chapter  GPA_SEM_III  GP_SEM_IV  \
0                              NaN         9.08       9.56
1                              NaN         8.77       8.52
2                              NaN         0.00       7.00
3                              NaN         7.31       8.07
4                              NaN         6.96       8.00
..                             ...          ...        ...
110                            NaN         0.00       0.00
111                            NaN         0.00       6.85
112                            NaN         7.08       7.52
113                            NaN         0.00       0.00
114                            NaN         0.00       6.93

     Number of Internships Completed/ Ongoing  Attendance
0                                         NaN         NaN
1                                         NaN         NaN
2                                         NaN         NaN
3                                         NaN         NaN
4                                         NaN         NaN
..                                        ...         ...
110                                       NaN         NaN
111                                       NaN         NaN
112                                       NaN         NaN
113                                       NaN         NaN
114                                       NaN         NaN

[115 rows x 15 columns]>

In [8]:
df.corr()

,Applied Mathematics - III,Applied Mathematics - IV,Discrete Structure and Graph Theory,Data Structures,Analysis Of Algorithm,Skill Based Lab (Java),Skill Based Lab (Python),SEM III Project Marks,SEM IV Project Marks,Member of any Student Chapter,GPA_SEM_III,GP_SEM_IV,Number of Internships Completed/ Ongoing,Attendance
Applied Mathematics - III,1.000000,0.783799,0.677680,0.660466,0.687216,0.027807,0.262948,NaN,NaN,NaN,0.695409,0.586120,NaN,NaN
Applied Mathematics - IV,0.783799,1.000000,0.635623,0.606226,0.710886,-0.103942,0.324198,NaN,NaN,NaN,0.598672,0.698434,NaN,NaN
Discrete Structure and Graph Theory,0.677680,0.635623,1.000000,0.678960,0.654661,0.089470,0.375854,NaN,NaN,NaN,0.652531,0.554483,NaN,NaN
Data Structures,0.660466,0.606226,0.678960,1.000000,0.644085,0.150777,0.445464,NaN,NaN,NaN,0.729013,0.547011,NaN,NaN
Analysis Of Algorithm,0.687216,0.710886,0.654661,0.644085,1.000000,-0.012883,0.359757,NaN,NaN,NaN,0.695125,0.651526,NaN,NaN
Skill Based Lab (Java),0.027807,-0.103942,0.089470,0.150777,-0.012883,1.000000,0.374605,NaN,NaN,NaN,0.119842,0.045806,NaN,NaN
Skill Based Lab (Python),0.262948,0.324198,0.375854,0.445464,0.359757,0.374605,1.000000,NaN,NaN,NaN,0.390668,0.320611,NaN,NaN
SEM III Project Marks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SEM IV Project Marks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Member of any Student Chapter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GPA_SEM_III,0.695409,0.598672,0.652531,0.729013,0.695125,0.119842,0.390668,NaN,NaN,NaN,1.000000,0.599205,NaN,NaN
GP_SEM_IV,0.586120,0.698434,0.554483,0.547011,0.651526,0.045806,0.320611,NaN,NaN,NaN,0.599205,1.000000,NaN,NaN
Number of Internships Completed/ Ongoing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Attendance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
del df['SEM III Project Marks']
del df['SEM IV Project Marks']
del df['Number of Internships Completed/ Ongoing']
del df['Attendance']
del df['Member of any Student Chapter']
del df['Timestamp']

In [10]:
df.head(10)

,Applied Mathematics - III,Applied Mathematics - IV,Discrete Structure and Graph Theory,Data Structures,Analysis Of Algorithm,Skill Based Lab (Java),Skill Based Lab (Python),GPA_SEM_III,GP_SEM_IV
0,94,93,82,70,86,47,46,9.08,9.56
1,90,79,64,80,70,46,37,8.77,8.52
2,19,71,48,40,49,42,35,0.00,7.00
3,71,69,62,54,65,46,38,7.31,8.07
4,64,80,62,43,69,45,32,6.96,8.00
5,67,70,57,78,60,43,42,7.08,7.73
6,96,94,88,78,71,45,47,9.54,9.21
7,90,92,87,85,81,46,40,9.54,9.77
8,83,81,89,66,77,42,35,9.08,9.22
9,26,58,65,60,54,45,42,0.00,6.56

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Applied Mathematics - III            115 non-null    int64
 1   Applied Mathematics - IV             115 non-null    int64
 2   Discrete Structure and Graph Theory  115 non-null    int64
 3   Data Structures                      115 non-null    int64
 4   Analysis Of Algorithm                115 non-null    int64
 5   Skill Based Lab (Java)               115 non-null    int64
 6   Skill Based Lab (Python)             115 non-null    int64
 7   GPA_SEM_III                          115 non-null    float64
 8   GP_SEM_IV                            115 non-null    float64
dtypes: float64(2), int64(7)
memory usage: 8.2 KB

In [12]:
df['avg_GPA'] = (df.GPA_SEM_III +df.GP_SEM_IV)/2

In [13]:
df.describe()

,Applied Mathematics - III,Applied Mathematics - IV,Discrete Structure and Graph Theory,Data Structures,Analysis Of Algorithm,Skill Based Lab (Java),Skill Based Lab (Python),GPA_SEM_III,GP_SEM_IV,avg_GPA
count,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000
mean,66.843478,72.260870,63.121739,61.504348,68.347826,43.043478,39.478261,6.519739,7.545565,7.032652
std,18.808635,17.109086,13.316754,14.366368,12.746546,2.763773,4.233011,2.920690,2.532678,2.439761
min,12.000000,19.000000,11.000000,28.000000,31.000000,34.000000,26.000000,0.000000,0.000000,0.000000
25%,56.000000,61.500000,53.000000,52.000000,60.000000,42.000000,37.000000,6.230000,7.350000,6.850000
50%,69.000000,75.000000,62.000000,63.000000,69.000000,44.000000,40.000000,7.310000,8.110000,7.655000
75%,82.000000,85.000000,73.500000,73.500000,78.500000,45.000000,43.000000,8.490000,9.065000,8.707500
max,99.000000,97.000000,89.000000,86.000000,91.000000,47.000000,48.000000,10.000000,10.000000,10.000000

In [14]:
df.head(5)

,Applied Mathematics - III,Applied Mathematics - IV,Discrete Structure and Graph Theory,Data Structures,Analysis Of Algorithm,Skill Based Lab (Java),Skill Based Lab (Python),GPA_SEM_III,GP_SEM_IV,avg_GPA
0,94,93,82,70,86,47,46,9.08,9.56,9.320
1,90,79,64,80,70,46,37,8.77,8.52,8.645
2,19,71,48,40,49,42,35,0.00,7.00,3.500
3,71,69,62,54,65,46,38,7.31,8.07,7.690
4,64,80,62,43,69,45,32,6.96,8.00,7.480