In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('G:/SEM 5/mini-project/dataset/final.csv', header=0)

In [3]:
df

,sex,famsize,Medu,Fedu,Mjob,Fjob,guardian,traveltime,studytime,failures,extra_learning,sports,internship,higher,freetime,goout,health,absences,GPA
0,F,GT3,4,4,at_home,teacher,mother,2,2,0,no,no,0,yes,3,4,3,4,9.08
1,F,GT3,1,1,at_home,other,father,1,2,0,no,no,1,yes,3,3,3,2,9.54
2,F,LE3,1,1,at_home,other,mother,1,2,0,no,no,2,yes,3,2,3,6,0.00
3,F,GT3,4,2,health,services,mother,1,3,0,no,yes,2,yes,2,2,5,0,7.54
4,F,GT3,3,3,other,other,father,1,2,0,no,no,0,yes,3,2,5,0,7.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,F,GT3,2,3,services,other,mother,1,3,1,no,yes,0,yes,4,2,5,4,0.00
645,F,LE3,3,1,teacher,services,mother,1,2,0,no,no,2,yes,3,4,1,4,6.92
646,F,GT3,1,1,other,other,mother,2,2,0,no,yes,0,yes,1,1,5,6,6.48
647,M,LE3,3,1,services,services,mother,2,1,0,no,no,0,yes,4,5,2,6,7.75
648,M,LE3,3,2,services,other,mother,3,1,0,no,no,1,yes,4,1,5,4,9.33

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sex             649 non-null    object
 1   famsize         649 non-null    object
 2   Medu            649 non-null    int64
 3   Fedu            649 non-null    int64
 4   Mjob            649 non-null    object
 5   Fjob            649 non-null    object
 6   guardian        649 non-null    object
 7   traveltime      649 non-null    int64
 8   studytime       649 non-null    int64
 9   failures        649 non-null    int64
 10  extra_learning  649 non-null    object
 11  sports          649 non-null    object
 12  internship      649 non-null    int64
 13  higher          649 non-null    object
 14  freetime        649 non-null    int64
 15  goout           649 non-null    int64
 16  health          649 non-null    int64
 17  absences        649 non-null    int64
 18  GPA             649 non-null    float64
dtypes: float64(1), int64(10), object(8)
memory usage: 96.5+ KB

In [5]:
df.corr()

,Medu,Fedu,traveltime,studytime,failures,internship,freetime,goout,health,absences,GPA
Medu,1.000000,0.647477,-0.265079,0.097006,-0.172210,0.007594,-0.019686,0.009536,0.004614,-0.008577,-0.142606
Fedu,0.647477,1.000000,-0.208288,0.050400,-0.165915,0.008339,0.006841,0.027690,0.044910,0.029859,-0.124648
traveltime,-0.265079,-0.208288,1.000000,-0.063154,0.097730,0.016449,0.000937,0.057454,-0.048261,-0.008149,0.144665
studytime,0.097006,0.050400,-0.063154,1.000000,-0.147441,0.011450,-0.068829,-0.075442,-0.056433,-0.118389,-0.063716
failures,-0.172210,-0.165915,0.097730,-0.147441,1.000000,-0.037106,0.108995,0.045078,0.035588,0.122779,0.068226
internship,0.007594,0.008339,0.016449,0.011450,-0.037106,1.000000,0.030804,0.012969,-0.090710,0.025092,-0.016598
freetime,-0.019686,0.006841,0.000937,-0.068829,0.108995,0.030804,1.000000,0.346352,0.084526,-0.018716,-0.018277
goout,0.009536,0.027690,0.057454,-0.075442,0.045078,0.012969,0.346352,1.000000,-0.015741,0.085374,0.032784
health,0.004614,0.044910,-0.048261,-0.056433,0.035588,-0.090710,0.084526,-0.015741,1.000000,-0.030235,-0.036893
absences,-0.008577,0.029859,-0.008149,-0.118389,0.122779,0.025092,-0.018716,0.085374,-0.030235,1.000000,0.001594
GPA,-0.142606,-0.124648,0.144665,-0.063716,0.068226,-0.016598,-0.018277,0.032784,-0.036893,0.001594,1.000000

In [6]:
df = pd.get_dummies(df)

In [7]:
df

,Medu,Fedu,traveltime,studytime,failures,internship,freetime,goout,health,absences,...,Fjob_teacher,guardian_father,guardian_mother,guardian_other,extra_learning_no,extra_learning_yes,sports_no,sports_yes,higher_no,higher_yes
0,4,4,2,2,0,0,3,4,3,4,...,1,0,1,0,1,0,1,0,0,1
1,1,1,1,2,0,1,3,3,3,2,...,0,1,0,0,1,0,1,0,0,1
2,1,1,1,2,0,2,3,2,3,6,...,0,0,1,0,1,0,1,0,0,1
3,4,2,1,3,0,2,2,2,5,0,...,0,0,1,0,1,0,0,1,0,1
4,3,3,1,2,0,0,3,2,5,0,...,0,1,0,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,2,3,1,3,1,0,4,2,5,4,...,0,0,1,0,1,0,0,1,0,1
645,3,1,1,2,0,2,3,4,1,4,...,0,0,1,0,1,0,1,0,0,1
646,1,1,2,2,0,0,1,1,5,6,...,0,0,1,0,1,0,0,1,0,1
647,3,1,2,1,0,0,4,5,2,6,...,0,0,1,0,1,0,1,0,0,1
648,3,2,3,1,0,1,4,1,5,4,...,0,0,1,0,1,0,1,0,0,1

In [8]:
new = df

In [9]:
# print(df['internship'].astype(int))

In [10]:
# new.to_csv("new.csv")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Medu                649 non-null    int64
 1   Fedu                649 non-null    int64
 2   traveltime          649 non-null    int64
 3   studytime           649 non-null    int64
 4   failures            649 non-null    int64
 5   internship          649 non-null    int64
 6   freetime            649 non-null    int64
 7   goout               649 non-null    int64
 8   health              649 non-null    int64
 9   absences            649 non-null    int64
 10  GPA                 649 non-null    float64
 11  sex_F               649 non-null    uint8
 12  sex_M               649 non-null    uint8
 13  famsize_GT3         649 non-null    uint8
 14  famsize_LE3         649 non-null    uint8
 15  Mjob_at_home        649 non-null    uint8
 16  Mjob_health         649 non-null    uint8
 17  Mjob_other          649 non-null    uint8
 18  Mjob_services       649 non-null    uint8
 19  Mjob_teacher        649 non-null    uint8
 20  Fjob_at_home        649 non-null    uint8
 21  Fjob_health         649 non-null    uint8
 22  Fjob_other          649 non-null    uint8
 23  Fjob_services       649 non-null    uint8
 24  Fjob_teacher        649 non-null    uint8
 25  guardian_father     649 non-null    uint8
 26  guardian_mother     649 non-null    uint8
 27  guardian_other      649 non-null    uint8
 28  extra_learning_no   649 non-null    uint8
 29  extra_learning_yes  649 non-null    uint8
 30  sports_no           649 non-null    uint8
 31  sports_yes          649 non-null    uint8
 32  higher_no           649 non-null    uint8
 33  higher_yes          649 non-null    uint8
dtypes: float64(1), int64(10), uint8(23)
memory usage: 70.5 KB

In [12]:
del df['sex_M']
del df['famsize_LE3']
del df['Mjob_health']
del df['Fjob_other']
del df['guardian_other']
del df['extra_learning_no']
del df['sports_no']
del df['higher_no']
# del df['internship']
# del df['OOPM_A']
# del df['OOPM_A']
# del df['OOPM_A']

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Medu                649 non-null    int64
 1   Fedu                649 non-null    int64
 2   traveltime          649 non-null    int64
 3   studytime           649 non-null    int64
 4   failures            649 non-null    int64
 5   internship          649 non-null    int64
 6   freetime            649 non-null    int64
 7   goout               649 non-null    int64
 8   health              649 non-null    int64
 9   absences            649 non-null    int64
 10  GPA                 649 non-null    float64
 11  sex_F               649 non-null    uint8
 12  famsize_GT3         649 non-null    uint8
 13  Mjob_at_home        649 non-null    uint8
 14  Mjob_other          649 non-null    uint8
 15  Mjob_services       649 non-null    uint8
 16  Mjob_teacher        649 non-null    uint8
 17  Fjob_at_home        649 non-null    uint8
 18  Fjob_health         649 non-null    uint8
 19  Fjob_services       649 non-null    uint8
 20  Fjob_teacher        649 non-null    uint8
 21  guardian_father     649 non-null    uint8
 22  guardian_mother     649 non-null    uint8
 23  extra_learning_yes  649 non-null    uint8
 24  sports_yes          649 non-null    uint8
 25  higher_yes          649 non-null    uint8
dtypes: float64(1), int64(10), uint8(15)
memory usage: 65.4 KB

In [14]:
# df.to_csv("new_final.csv")

In [15]:
# df = pd.read_csv('G:/SEM 5/mini-project/new_final.csv', header=0)

In [16]:
df.head()

,Medu,Fedu,traveltime,studytime,failures,internship,freetime,goout,health,absences,...,Mjob_teacher,Fjob_at_home,Fjob_health,Fjob_services,Fjob_teacher,guardian_father,guardian_mother,extra_learning_yes,sports_yes,higher_yes
0,4,4,2,2,0,0,3,4,3,4,...,0,0,0,0,1,0,1,0,0,1
1,1,1,1,2,0,1,3,3,3,2,...,0,0,0,0,0,1,0,0,0,1
2,1,1,1,2,0,2,3,2,3,6,...,0,0,0,0,0,0,1,0,0,1
3,4,2,1,3,0,2,2,2,5,0,...,0,0,0,1,0,0,1,0,1,1
4,3,3,1,2,0,0,3,2,5,0,...,0,0,0,0,0,1,0,0,0,1

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X = df.values

In [19]:
X

array([[4., 4., 2., ..., 0., 0., 1.],
       [1., 1., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 0., 0., 1.],
       ...,
       [1., 1., 2., ..., 0., 1., 1.],
       [3., 1., 2., ..., 0., 0., 1.],
       [3., 2., 3., ..., 0., 0., 1.]])

In [20]:
X = df.drop("GPA", axis = 1)

In [21]:
y = df['GPA'].values

In [22]:
# y

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [24]:
print("X_train : \n", X_train )
print("X_test : \n", X_test )
print("y_train : \n", y_train )
print("y_test : \n", y_test )
# X_test.to_csv("X_test.csv")

X_train :
      Medu  Fedu  traveltime  studytime  failures  internship  freetime  goout  \
561     1     1           2          2         0           2         3      3
452     2     2           3          2         0           1         4      5
89      4     4           1          2         0           2         1      3
299     2     1           2          2         0           1         2      3
231     3     3           1          2         0           0         2      4
..    ...   ...         ...        ...       ...         ...       ...    ...
9       3     4           1          2         0           0         5      1
359     3     4           1          3         0           1         3      4
192     4     2           1          1         0           2         3      3
629     1     2           1          1         0           0         5      5
559     1     0           3          1         1           1         3      2

     health  absences  ...  Mjob_teacher  Fjob_at_home  Fjob_health  \
561       5         6  ...             0             1            0
452       4         4  ...             0             0            0
89        5         6  ...             1             0            1
299       2         8  ...             0             0            0
231       4        10  ...             0             0            1
..      ...       ...  ...           ...           ...          ...
9         5         0  ...             0             0            0
359       5         2  ...             0             0            0
192       3         8  ...             1             0            0
629       1         4  ...             0             0            0
559       4         0  ...             0             1            0

     Fjob_services  Fjob_teacher  guardian_father  guardian_mother  \
561              0             0                0                1
452              0             0                0                1
89               0             0                0                1
299              0             0                0                0
231              0             0                1                0
..             ...           ...              ...              ...
9                0             0                0                1
359              1             0                1                0
192              1             0                0                1
629              0             0                0                1
559              0             0                0                0

     extra_learning_yes  sports_yes  higher_yes
561                   0           1           1
452                   0           0           1
89                    0           0           1
299                   1           1           0
231                   0           0           1
..                  ...         ...         ...
9                     0           1           1
359                   0           1           1
192                   0           1           1
629                   0           1           1
559                   0           0           1

[454 rows x 25 columns]
X_test :
      Medu  Fedu  traveltime  studytime  failures  internship  freetime  goout  \
532     2     1           2          2         0           0         2      2
375     0     2           2          3         0           0         3      3
306     3     4           2          2         0           0         2      5
625     2     3           2          1         0           2         2      3
480     2     3           1          1         1           1         4      4
..    ...   ...         ...        ...       ...         ...       ...    ...
478     1     1           2          2         3           1         4      3
636     4     4           1          2         0           0         2      4
632     1     1           2          2         1           1         3      3
96      4     3           2          1         0           0         3      3
350     2     1           2          3         1           1         3      1

     health  absences  ...  Mjob_teacher  Fjob_at_home  Fjob_health  \
532       5         2  ...             0             0            0
375       2         0  ...             0             1            0
306       1         6  ...             0             0            0
625       4         0  ...             0             0            0
480       2         0  ...             0             0            0
..      ...       ...  ...           ...           ...          ...
478       1         0  ...             0             0            0
636       2         4  ...             1             0            0
632       3         4  ...             0             0            0
96        4         6  ...             0             0            0
350       5         0  ...             0             0            0

     Fjob_services  Fjob_teacher  guardian_father  guardian_mother  \
532              1             0                0                1
375              0             0                1                0
306              0             0                0                1
625              1             0                1                0
480              1             0                0                0
..             ...           ...              ...              ...
478              0             0                1                0
636              0             1                1                0
632              0             0                0                0
96               0             0                0                1
350              1             0                0                1

     extra_learning_yes  sports_yes  higher_yes
532                   0           0           1
375                   0           0           1
306                   0           1           1
625                   0           0           1
480                   0           0           0
..                  ...         ...         ...
478                   0           0           1
636                   0           1           1
632                   0           0           1
96                    1           1           1
350                   0           1           1

[195 rows x 25 columns]
y_train :
 [ 6.62   0.     6.96   7.59   7.85   6.73   7.5    9.23   6.06   7.69
  7.96   7.     6.15   8.11   0.     7.38   9.81   9.08   7.48  10.
  5.78   7.58   6.8    5.62   7.22   8.     6.64  10.     0.     7.81
  9.04   7.48   0.     7.29   9.22   8.     7.73   0.     6.81   7.42
  7.5    9.85   9.37   7.56   7.38   3.46   8.38   7.54   9.63   6.08
  9.92   8.58  10.     8.46   7.19   8.62   0.     7.96   9.7    7.15
  7.73   8.04   0.     7.69  10.     6.68   6.38   8.62   9.62   9.04
  7.08   6.5    9.54   8.81   7.5    8.5    9.04   7.19  10.     8.
  8.92  10.     9.23   7.43   0.     6.33   6.15   8.     6.73   8.41
  7.73   8.88   6.81   6.5    8.77   6.96   6.36   6.85   7.81   0.
  9.63   8.88   8.31   8.29   0.     8.27   7.69   7.58   9.14   7.69
  0.     7.3    7.78   8.15   7.65   9.33   9.77   8.74   6.74   9.02
  7.4    0.     8.12   9.58  10.     8.92   6.11   6.59   6.65   8.96
  7.12   7.85   7.12   6.338  0.     8.5    9.1    8.27   7.44   7.33
 10.     8.62  10.     9.15   8.37   0.     9.92   7.37   7.44   9.85
  6.56   8.89   9.23   7.7   10.     5.31   7.68  10.     0.     7.67
  7.41   7.31   8.04   8.12   6.54   0.     8.96   9.21   7.92   8.5
  9.67   0.     5.96   6.96   6.23   8.92  10.     7.06   5.85   9.31
  7.81   8.62   8.62   7.08   8.08   0.     9.08   7.63   9.54   9.19
  6.65   6.69  10.     8.58   8.89   7.56  10.     8.92   0.     6.46
  0.     0.     6.7    9.96   7.52   7.36   7.11  10.     6.69   0.
  7.38   6.92   6.81   9.31   7.     9.85   7.56   9.7    7.63   7.41
  7.81   8.44   9.33   9.31   8.38   7.58  10.     6.7    7.77   8.65
  9.96  10.     7.88   5.63   7.26   9.17   0.     8.15   7.46   8.15
  6.96   0.     5.93   0.    10.     6.7    0.     8.38   6.38  10.
  8.54   6.81   8.56   6.85   8.     7.81  10.     7.38   8.59   7.81
  8.12   7.15   9.38   8.54   8.42   7.04   9.92   7.85   7.38   8.26
 10.     8.41   0.     6.74   8.35   7.33   0.     6.14   8.96   8.89
  8.52   4.96   8.12   7.65   6.46   7.7   10.     7.59   0.     9.96
  7.89   7.89   6.63   7.92   8.92   0.     7.72   8.     8.52   7.75
  6.67   8.95   0.     0.     0.     7.15   8.26   8.12   9.23   7.11
  6.5    7.96   7.77  10.     9.11   7.38   8.37   7.77   6.64   9.54
  9.15   0.     8.18   6.46   7.65   6.23   0.     7.54   8.89   7.42
  8.26   6.59   7.89  10.     7.48   0.     8.15   7.85   7.37   7.41
  5.56   6.85   7.15   6.69   8.22   8.67   9.96   7.56   7.58   7.64
  8.46   8.3    9.77   9.36   9.08   5.85   7.     8.46   7.54   6.62
  7.69   8.31   7.23   8.     7.95   7.54   8.62   6.65   8.27   7.37
  7.5    9.96   7.69   8.24   8.5    8.27   7.11   6.58   7.46   7.73
  8.81   7.78   9.37   7.88  10.     6.89   8.52   7.08   8.08   7.52
  9.03   9.77   8.29   7.46   7.26   8.85   5.65   6.73   7.92   7.31
  9.23   7.5    0.     7.93   6.08   6.74   7.41   9.85   8.6    7.54
  7.77   9.26   0.     8.54   0.     9.04   7.98   8.63   8.54   8.07
  6.96   8.88   8.52   7.96   7.23   8.65   7.44   8.67   8.31   9.19
  8.07   0.     7.25   7.48   9.56   6.85   8.     7.48   8.44   8.58
  7.35   7.81   7.59   7.73   9.42   7.62   7.88  10.     8.11   0.
  6.58   9.33   6.92   7.96 ]
y_test :
 [ 8.58  7.35  8.37 10.    8.5   7.12  6.67  7.41  9.23  5.85  7.96  6.88
  9.3   7.67  0.    6.07  9.3   8.23  9.15  8.73  7.08  7.93  6.3   7.37
  7.27  8.77  0.    9.96  8.67  6.48  8.46  7.42  6.58  9.14  6.67 10.
  7.27  8.92  8.88  0.    8.31  8.69  8.73  6.59  9.77  6.88  9.37  8.46
  7.54  7.69  8.52  8.12  6.15  6.08  9.18  7.87  8.93  6.8   9.11  7.73
  7.65  8.5   8.5  10.    9.38  7.08  8.42  7.3   7.04  9.38  7.15  7.81
  6.56  8.63  7.85  8.19  7.68  7.35  6.63  7.18  8.08  7.42  9.92  8.22
  6.04  7.84  7.27  6.89  9.38  7.31  6.8   0.    9.67  8.51  9.    8.73
  6.41  9.54  7.27  8.77  8.04 10.    8.62  0.    8.69  0.    8.62  0.
  7.12  6.77  6.92  8.62  6.07  7.92  8.    9.73 10.    6.77  8.73  7.11
 10.    7.88  0.    6.92  8.07  8.27  6.74  6.38  8.81  8.67  7.62  6.77
  7.92  6.11  9.15  9.77  6.69  8.58  8.46  9.54  6.93  7.63  6.5   6.27
  8.41  9.08  7.54  7.56  9.81  8.7   6.81  9.23  7.67  7.23  7.37  7.59
  7.52  8.   10.    6.3   9.78  8.52  8.62  6.96  7.59  8.11  7.62  6.69
  8.15  8.59  7.42  8.58  7.74  7.37  8.92  7.96  9.96  9.33 10.    7.19
  8.11  0.    9.52  8.43  8.    6.83  7.06  7.43  8.92  7.75  8.35  8.85
  7.    5.04  5.62]

In [25]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [26]:
regressor.score(X_test, y_test)

-0.10647607017073568

In [27]:
y_pred = regressor.predict(X_test)
y_pred

array([6.76326813, 7.89668163, 7.02248359, 8.21676997, 8.25650846,
       6.11294893, 6.74774879, 7.11507547, 6.22393932, 7.16293441,
       7.25001763, 7.69253867, 7.78587747, 7.20663181, 6.12417676,
       7.08028341, 6.61498164, 7.30028266, 8.43845129, 8.37528605,
       7.42775315, 6.8849488 , 6.46587146, 6.61116261, 7.10277462,
       7.34915574, 6.92514281, 7.64467412, 7.72652598, 7.52436427,
       8.01629579, 7.82705087, 7.88010384, 7.9794362 , 7.56900996,
       5.76137776, 8.22424296, 6.79809749, 7.02017742, 6.27234446,
       6.67036638, 8.22605775, 8.24245849, 6.82397587, 7.21619048,
       6.82933636, 7.11350081, 8.02557456, 6.98721389, 7.77743448,
       7.03891344, 6.92837723, 5.83327402, 6.8028913 , 8.38285641,
       8.24900731, 8.16843454, 8.06254151, 7.03960944, 6.13384472,
       6.58692626, 8.17480321, 6.93773305, 7.80322343, 7.33588331,
       7.49684997, 7.39532354, 7.74773689, 7.00932923, 7.41990736,
       8.47531505, 7.6282716 , 8.68299402, 6.40428295, 7.31859902,
       8.00095207, 7.45386932, 6.79885968, 7.20966006, 6.75760264,
       5.97217225, 8.00056608, 8.92800854, 5.62496676, 7.53224929,
       7.04971066, 6.93710166, 7.18223438, 7.28382706, 7.96081378,
       7.94823585, 7.54212769, 6.8563481 , 7.83149451, 6.94453856,
       7.96463225, 7.31330926, 7.5031052 , 7.45809751, 6.71877374,
       7.68438436, 7.41103174, 7.07145305, 7.57883169, 8.00805698,
       7.58466281, 6.18549391, 8.03664622, 7.06763487, 6.52012833,
       5.15592178, 6.6607419 , 7.35497026, 6.08396063, 7.08420837,
       9.05263465, 8.21087817, 6.91452308, 5.8215444 , 8.05982457,
       8.80184376, 7.71131501, 7.09260971, 6.91294163, 7.09245154,
       7.2600806 , 7.4435979 , 7.33335037, 7.68626513, 8.24545272,
       6.48478636, 7.99162742, 7.1481061 , 7.85946007, 7.8517391 ,
       6.83498477, 8.33395046, 7.68948062, 6.48447722, 8.27259347,
       7.3407865 , 7.31602781, 7.6764525 , 7.37581882, 7.15921298,
       6.54178515, 7.67991612, 7.08517864, 6.36101616, 7.55724027,
       5.57064541, 6.74400245, 7.33556707, 8.20541486, 6.90059836,
       7.23507225, 6.86835347, 7.06965028, 6.35485691, 7.08471731,
       5.66438753, 6.21682172, 6.45910513, 7.91766821, 6.93624586,
       7.65523052, 6.04272728, 7.3667499 , 7.59944484, 7.30696165,
       7.31158815, 7.40585609, 6.53342809, 7.41874655, 6.72489049,
       7.89373788, 8.7082923 , 7.46874814, 7.74303105, 7.47236669,
       6.94387216, 8.23632734, 8.01966331, 7.43132855, 9.50958775,
       7.1773677 , 7.32094653, 7.271704  , 7.3518799 , 7.72299558,
       8.08596039, 7.99909141, 7.87704186, 7.09702551, 8.13063392])

In [28]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 6.76  8.58]
 [ 7.9   7.35]
 [ 7.02  8.37]
 [ 8.22 10.  ]
 [ 8.26  8.5 ]
 [ 6.11  7.12]
 [ 6.75  6.67]
 [ 7.12  7.41]
 [ 6.22  9.23]
 [ 7.16  5.85]
 [ 7.25  7.96]
 [ 7.69  6.88]
 [ 7.79  9.3 ]
 [ 7.21  7.67]
 [ 6.12  0.  ]
 [ 7.08  6.07]
 [ 6.61  9.3 ]
 [ 7.3   8.23]
 [ 8.44  9.15]
 [ 8.38  8.73]
 [ 7.43  7.08]
 [ 6.88  7.93]
 [ 6.47  6.3 ]
 [ 6.61  7.37]
 [ 7.1   7.27]
 [ 7.35  8.77]
 [ 6.93  0.  ]
 [ 7.64  9.96]
 [ 7.73  8.67]
 [ 7.52  6.48]
 [ 8.02  8.46]
 [ 7.83  7.42]
 [ 7.88  6.58]
 [ 7.98  9.14]
 [ 7.57  6.67]
 [ 5.76 10.  ]
 [ 8.22  7.27]
 [ 6.8   8.92]
 [ 7.02  8.88]
 [ 6.27  0.  ]
 [ 6.67  8.31]
 [ 8.23  8.69]
 [ 8.24  8.73]
 [ 6.82  6.59]
 [ 7.22  9.77]
 [ 6.83  6.88]
 [ 7.11  9.37]
 [ 8.03  8.46]
 [ 6.99  7.54]
 [ 7.78  7.69]
 [ 7.04  8.52]
 [ 6.93  8.12]
 [ 5.83  6.15]
 [ 6.8   6.08]
 [ 8.38  9.18]
 [ 8.25  7.87]
 [ 8.17  8.93]
 [ 8.06  6.8 ]
 [ 7.04  9.11]
 [ 6.13  7.73]
 [ 6.59  7.65]
 [ 8.17  8.5 ]
 [ 6.94  8.5 ]
 [ 7.8  10.  ]
 [ 7.34  9.38]
 [ 7.5   7.08]
 [ 7.4   8.42]
 [ 7.75  7.3 ]
 [ 7.01  7.04]
 [ 7.42  9.38]
 [ 8.48  7.15]
 [ 7.63  7.81]
 [ 8.68  6.56]
 [ 6.4   8.63]
 [ 7.32  7.85]
 [ 8.    8.19]
 [ 7.45  7.68]
 [ 6.8   7.35]
 [ 7.21  6.63]
 [ 6.76  7.18]
 [ 5.97  8.08]
 [ 8.    7.42]
 [ 8.93  9.92]
 [ 5.62  8.22]
 [ 7.53  6.04]
 [ 7.05  7.84]
 [ 6.94  7.27]
 [ 7.18  6.89]
 [ 7.28  9.38]
 [ 7.96  7.31]
 [ 7.95  6.8 ]
 [ 7.54  0.  ]
 [ 6.86  9.67]
 [ 7.83  8.51]
 [ 6.94  9.  ]
 [ 7.96  8.73]
 [ 7.31  6.41]
 [ 7.5   9.54]
 [ 7.46  7.27]
 [ 6.72  8.77]
 [ 7.68  8.04]
 [ 7.41 10.  ]
 [ 7.07  8.62]
 [ 7.58  0.  ]
 [ 8.01  8.69]
 [ 7.58  0.  ]
 [ 6.19  8.62]
 [ 8.04  0.  ]
 [ 7.07  7.12]
 [ 6.52  6.77]
 [ 5.16  6.92]
 [ 6.66  8.62]
 [ 7.35  6.07]
 [ 6.08  7.92]
 [ 7.08  8.  ]
 [ 9.05  9.73]
 [ 8.21 10.  ]
 [ 6.91  6.77]
 [ 5.82  8.73]
 [ 8.06  7.11]
 [ 8.8  10.  ]
 [ 7.71  7.88]
 [ 7.09  0.  ]
 [ 6.91  6.92]
 [ 7.09  8.07]
 [ 7.26  8.27]
 [ 7.44  6.74]
 [ 7.33  6.38]
 [ 7.69  8.81]
 [ 8.25  8.67]
 [ 6.48  7.62]
 [ 7.99  6.77]
 [ 7.15  7.92]
 [ 7.86  6.11]
 [ 7.85  9.15]
 [ 6.83  9.77]
 [ 8.33  6.69]
 [ 7.69  8.58]
 [ 6.48  8.46]
 [ 8.27  9.54]
 [ 7.34  6.93]
 [ 7.32  7.63]
 [ 7.68  6.5 ]
 [ 7.38  6.27]
 [ 7.16  8.41]
 [ 6.54  9.08]
 [ 7.68  7.54]
 [ 7.09  7.56]
 [ 6.36  9.81]
 [ 7.56  8.7 ]
 [ 5.57  6.81]
 [ 6.74  9.23]
 [ 7.34  7.67]
 [ 8.21  7.23]
 [ 6.9   7.37]
 [ 7.24  7.59]
 [ 6.87  7.52]
 [ 7.07  8.  ]
 [ 6.35 10.  ]
 [ 7.08  6.3 ]
 [ 5.66  9.78]
 [ 6.22  8.52]
 [ 6.46  8.62]
 [ 7.92  6.96]
 [ 6.94  7.59]
 [ 7.66  8.11]
 [ 6.04  7.62]
 [ 7.37  6.69]
 [ 7.6   8.15]
 [ 7.31  8.59]
 [ 7.31  7.42]
 [ 7.41  8.58]
 [ 6.53  7.74]
 [ 7.42  7.37]
 [ 6.72  8.92]
 [ 7.89  7.96]
 [ 8.71  9.96]
 [ 7.47  9.33]
 [ 7.74 10.  ]
 [ 7.47  7.19]
 [ 6.94  8.11]
 [ 8.24  0.  ]
 [ 8.02  9.52]
 [ 7.43  8.43]
 [ 9.51  8.  ]
 [ 7.18  6.83]
 [ 7.32  7.06]
 [ 7.27  7.43]
 [ 7.35  8.92]
 [ 7.72  7.75]
 [ 8.09  8.35]
 [ 8.    8.85]
 [ 7.88  7.  ]
 [ 7.1   5.04]
 [ 8.13  5.62]]

In [29]:
# a = regressor.predict([[2,1,2,2,0,0,2,2,5,2,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1]])

In [30]:
# a

In [31]:
y_test_a = regressor.predict(X_test)

In [32]:
y_train_a = regressor.predict(X_train)

In [33]:
from sklearn.metrics import r2_score

In [34]:
r2_score(y_test, y_test_a)

-0.10647607017073568

In [35]:
df.corr()

,Medu,Fedu,traveltime,studytime,failures,internship,freetime,goout,health,absences,...,Mjob_teacher,Fjob_at_home,Fjob_health,Fjob_services,Fjob_teacher,guardian_father,guardian_mother,extra_learning_yes,sports_yes,higher_yes
Medu,1.000000,0.647477,-0.265079,0.097006,-0.172210,0.007594,-0.019686,0.009536,0.004614,-0.008577,...,0.449847,-0.097313,0.155576,-0.012576,0.258136,-0.040792,0.091562,0.113973,0.119354,0.213896
Fedu,0.647477,1.000000,-0.208288,0.050400,-0.165915,0.008339,0.006841,0.027690,0.044910,0.029859,...,0.312130,-0.107575,0.227081,0.026575,0.348874,0.086158,-0.044450,0.094628,0.079700,0.191735
traveltime,-0.265079,-0.208288,1.000000,-0.063154,0.097730,0.016449,0.000937,0.057454,-0.048261,-0.008149,...,-0.097961,-0.040854,-0.089981,-0.031740,-0.040209,0.019455,-0.066130,-0.044842,-0.033376,-0.071958
studytime,0.097006,0.050400,-0.063154,1.000000,-0.147441,0.011450,-0.068829,-0.075442,-0.056433,-0.118389,...,0.035469,-0.008220,0.096471,0.014716,-0.020335,0.015804,-0.018076,-0.002314,0.070080,0.188256
failures,-0.172210,-0.165915,0.097730,-0.147441,1.000000,-0.037106,0.108995,0.045078,0.035588,0.122779,...,-0.123945,0.038892,-0.057688,-0.006725,-0.079352,-0.073165,-0.056527,0.069416,0.000561,-0.309400
internship,0.007594,0.008339,0.016449,0.011450,-0.037106,1.000000,0.030804,0.012969,-0.090710,0.025092,...,0.025299,0.039102,-0.030311,0.031570,-0.008779,0.029207,-0.008289,-0.055306,0.070549,-0.016616
freetime,-0.019686,0.006841,0.000937,-0.068829,0.108995,0.030804,1.000000,0.346352,0.084526,-0.018716,...,0.060821,0.032370,-0.024966,-0.051132,0.003269,-0.043488,0.022349,-0.049574,0.150329,-0.102618
goout,0.009536,0.027690,0.057454,-0.075442,0.045078,0.012969,0.346352,1.000000,-0.015741,0.085374,...,-0.055594,-0.014744,0.026582,-0.027686,-0.038139,-0.056511,0.042602,-0.006683,0.088582,-0.069105
health,0.004614,0.044910,-0.048261,-0.056433,0.035588,-0.090710,0.084526,-0.015741,1.000000,-0.030235,...,0.031889,-0.045595,0.096117,-0.076209,0.017218,-0.015172,0.009374,0.063203,0.013001,0.017290
absences,-0.008577,0.029859,-0.008149,-0.118389,0.122779,0.025092,-0.018716,0.085374,-0.030235,1.000000,...,-0.041773,0.044978,-0.025463,-0.035095,-0.017044,-0.094642,0.005036,-0.035959,-0.015115,-0.129891
GPA,-0.142606,-0.124648,0.144665,-0.063716,0.068226,-0.016598,-0.018277,0.032784,-0.036893,0.001594,...,0.003968,0.033870,-0.094018,0.049428,0.007526,0.018913,-0.040254,0.028564,-0.028680,-0.072184
sex_F,-0.119127,-0.083913,-0.040880,0.206214,-0.073888,0.004511,-0.146305,-0.058178,-0.139547,-0.021336,...,-0.104647,0.053666,0.007233,-0.047612,-0.044416,-0.039055,0.030708,-0.079300,-0.124707,0.058134
famsize_GT3,0.014325,0.039538,-0.012794,0.010945,0.066068,-0.081372,0.021257,0.004312,-0.002448,-0.004645,...,-0.039768,-0.021608,-0.021832,-0.003410,0.083334,0.010049,-0.017646,0.050253,0.014790,-0.004523
Mjob_at_home,-0.376636,-0.198240,0.173772,-0.039569,0.096358,-0.001370,-0.022907,-0.038650,-0.074573,-0.009848,...,-0.181035,0.142939,-0.057169,-0.013969,-0.091026,-0.025273,-0.005354,-0.001797,-0.049553,-0.155758
Mjob_other,-0.224335,-0.197974,0.034973,-0.004220,-0.001301,-0.004979,-0.019520,0.008832,-0.033425,0.026381,...,-0.286946,-0.034508,-0.104616,-0.154132,-0.086812,0.068072,-0.109205,-0.033171,-0.077004,-0.026252
Mjob_services,0.130272,0.104368,-0.072497,0.029369,0.011652,-0.015385,0.012552,0.044643,0.070931,0.071283,...,-0.181882,-0.027718,-0.016785,0.177884,0.007544,-0.018388,0.063294,0.045041,0.060531,0.042486
Mjob_teacher,0.449847,0.312130,-0.097961,0.035469,-0.123945,0.025299,0.060821,-0.055594,0.031889,-0.041773,...,1.000000,-0.053036,0.064971,0.010064,0.257344,-0.103724,0.123488,-0.006743,0.098696,0.105923
Fjob_at_home,-0.097313,-0.107575,-0.040854,-0.008220,0.038892,0.039102,0.032370,-0.014744,-0.045595,0.044978,...,-0.053036,1.000000,-0.050420,-0.163586,-0.063746,0.016210,-0.033454,0.012547,0.032767,-0.092137
Fjob_health,0.155576,0.227081,-0.089981,0.096471,-0.057688,-0.030311,-0.024966,0.026582,0.096117,-0.025463,...,0.064971,-0.050420,1.000000,-0.119205,-0.046451,0.070246,-0.038682,-0.013400,-0.002723,0.039076
Fjob_services,-0.012576,0.026575,-0.031740,0.014716,-0.006725,0.031570,-0.051132,-0.027686,-0.076209,-0.035095,...,0.010064,-0.163586,-0.119205,1.000000,-0.150708,0.099804,-0.059257,0.001782,0.035401,0.025007
Fjob_teacher,0.258136,0.348874,-0.040209,-0.020335,-0.079352,-0.008779,0.003269,-0.038139,0.017218,-0.017044,...,0.257344,-0.063746,-0.046451,-0.150708,1.000000,0.039855,-0.003512,-0.032951,0.034036,0.061747
guardian_father,-0.040792,0.086158,0.019455,0.015804,-0.073165,0.029207,-0.043488,-0.056511,-0.015172,-0.094642,...,-0.103724,0.016210,0.070246,0.099804,0.039855,1.000000,-0.850569,-0.064063,-0.030944,0.026692
guardian_mother,0.091562,-0.044450,-0.066130,-0.018076,-0.056527,-0.008289,0.022349,0.042602,0.009374,0.005036,...,0.123488,-0.033454,-0.038682,-0.059257,-0.003512,-0.850569,1.000000,0.037643,0.041487,0.080524
extra_learning_yes,0.113973,0.094628,-0.044842,-0.002314,0.069416,-0.055306,-0.049574,-0.006683,0.063203,-0.035959,...,-0.006743,0.012547,-0.013400,0.001782,-0.032951,-0.064063,0.037643,1.000000,0.065781,0.024112
sports_yes,0.119354,0.079700,-0.033376,0.070080,0.000561,0.070549,0.150329,0.088582,0.013001,-0.015115,...,0.098696,0.032767,-0.002723,0.035401,0.034036,-0.030944,0.041487,0.065781,1.000000,0.044908
higher_yes,0.213896,0.191735,-0.071958,0.188256,-0.309400,-0.016616,-0.102618,-0.069105,0.017290,-0.129891,...,0.105923,-0.092137,0.039076,0.025007,0.061747,0.026692,0.080524,0.024112,0.044908,1.000000

In [36]:
abc = df.corr()

In [37]:
abc.to_csv("final_corr.csv")